kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-product-api
spec:
  selector:
    matchLabels:
      app: flask-product-api
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-product-api
    spec:
      containers:
        - name: flask-product-api
          image: flask_product_api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---